### ISSUE TITLE
Windows file naming prohibits "|" symbol

### ISSUE THREAD

**Issue by ne1stadt** [ClaudinaRattaro/Py5cheSim#1]
Unfortunately, Windows file naming does not support "|" symbol, so if ran on Windows machine following error occurs:

OSError: [Errno 22] Invalid argument: 'Figures/PLR-DL_BW=[10]|Slice=eMBB|IntraSliceSched=.png'

(Results.py -> 320 and 347 lines)

Possible solution: replace with "_")

**Comment by ClaudinaRattaro** [comment]
Thanks, we will work on Windows compatibility in our next version.
