### ISSUE TITLE
Confusing description

### ISSUE THREAD

**Issue by ne1stadt** [ClaudinaRattaro/Py5cheSim#2]
simpulation.py -> 68 line

"""
UEgroupN = UEgroup(nuDL,nuUL,pszDL,pszUL,parrDL,parrUL,label,dly,avlty,schedulerType,mimo_mode,layers,cell,hdr,t_sim,measInterv,env,sinr):
"""
hdr parameter is not used anymore, so it's presence in description confuses :D

**Comment by ClaudinaRattaro** [comment]
see https://github.com/linglesloggia/py5chesim, it is the improved version of the simulator (version 2 )
it is related to article: https://www.colibri.udelar.edu.uy/jspui/bitstream/20.500.12008/31723/1/PIRB22.pdf
