### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by No3men60** [ClaudinaRattaro/Py5cheSim#3]
Hi, 
Is it possible to have the latest version?

**Comment by ClaudinaRattaro** [comment]
Here you have two new versions:

1) In https://github.com/linglesloggia/py5chesim is the improved version of the simulator (version 2 )
it is related to article: https://www.colibri.udelar.edu.uy/jspui/bitstream/20.500.12008/31723/1/PIRB22.pdf

2) in this repository: https://github.com/charluy/PFC we have integrated the framework deepmimo (https://deepmimo.net/) as an input of py5chesim (improving the channel model and mimo feature)

we are working on version 3.

**Comment by No3men60** [comment]
Claudina,
Thank you very much! Have a great day!
